# Generated by Django 4.2.2 on 2023-06-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_favorite_favorite_unique_favor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favor',
        ),
    ]
