# Generated by Django 4.2.2 on 2023-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0010_shopping_cart_shopping_cart_unique_shoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
