# Generated by Django 4.2.2 on 2023-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0012_remove_recipe_favorite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=50),
        ),
    ]
