# Generated by Django 4.2.2 on 2023-06-27 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0014_alter_favorite_recipe_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_cart',
            new_name='ShoppingCart',
        ),
    ]
