# Generated by Django 4.2.2 on 2023-07-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0016_alter_favorite_options_alter_follow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
