# Generated by Django 4.2.2 on 2023-06-30 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.UUIDField(default=uuid.UUID('4cdb0637-c1a1-4ab8-b2e0-e566d6d9c2cb'), verbose_name='Пароль'),
        ),
    ]
